// src/lib/views/tools/ImageSearchTool.svelte
<script lang="ts">
  import { open } from "@tauri-apps/plugin-dialog";

  import {
    getRowsByIds,
    searchSimilarImages,
    type RowRecord,
    type SimilarImageMatch,
  } from "../../api";
  import { errorText, formatCount } from "../../stores/app-state.svelte";
  import Thumbnail from "../../ui/Thumbnail.svelte";

  let queryPath = $state<string | null>(null);
  let matches = $state<SimilarImageMatch[]>([]);
  let rows = $state<Map<number, RowRecord>>(new Map());
  let searching = $state(false);
  let searched = $state(false);
  let error = $state<string | null>(null);

  const queryName = $derived(queryPath?.split(/[\\/]/).pop() ?? null);

  async function chooseAndSearch(): Promise<void> {
    const selection = await open({
      multiple: false,
      directory: false,
      title: "选择用于搜索的图片",
      filters: [
        {
          name: "图片",
          extensions: ["png", "jpg", "jpeg", "bmp", "gif", "webp", "tiff"],
        },
      ],
    });
    if (typeof selection !== "string") return;

    queryPath = selection;
    matches = [];
    rows = new Map();
    searched = false;
    searching = true;
    error = null;
    try {
      const result = await searchSimilarImages(selection, 10);
      const records = result.length > 0
        ? await getRowsByIds(result.map(match => match.rowId))
        : [];
      matches = result;
      rows = new Map(records.map(row => [row.id, row]));
      searched = true;
    } catch (cause) {
      error = errorText(cause);
    } finally {
      searching = false;
    }
  }

  function distanceLabel(distance: number): string {
    if (distance === 0) return "完全匹配";
    if (distance <= 3) return "极高相似";
    if (distance <= 6) return "高度相似";
    return "可能相似";
  }

  function rowName(rowId: number): string {
    const row = rows.get(rowId);
    const path = row?.imagePath ?? row?.storedImagePath;
    return path?.split(/[\\/]/).pop() ?? `图片 #${rowId}`;
  }
</script>

<div class="tool-page">
  <section class="intro-card">
    <div>
      <h3>选择一张参考图片</h3>
      <p>工具会计算参考图的感知哈希，并返回距离不超过 10 的库内图片。</p>
    </div>
    <button
      type="button"
      class="btn btn-primary"
      disabled={searching}
      onclick={() => void chooseAndSearch()}
    >
      {searching ? "搜索中…" : queryPath ? "换一张图片" : "选择图片…"}
    </button>
  </section>

  {#if queryName}
    <div class="query-row">
      <span>参考图片</span>
      <strong title={queryPath}>{queryName}</strong>
    </div>
  {/if}

  {#if error}
    <p class="message error">{error}</p>
  {:else if searched && matches.length === 0}
    <div class="empty-result">
      <strong>没有找到相似图片</strong>
      <span>可以先到“资料库维护”刷新感知哈希后再试。</span>
    </div>
  {:else if matches.length > 0}
    <div class="result-heading">
      <strong>搜索结果</strong>
      <span>{formatCount(matches.length)} 张</span>
    </div>
    <div class="results-grid">
      {#each matches as match (match.rowId)}
        <article class="result-card">
          <div class="thumbnail">
            <Thumbnail rowId={match.rowId} hasImage={true} alt={rowName(match.rowId)} />
          </div>
          <div class="card-info">
            <strong title={rowName(match.rowId)}>{rowName(match.rowId)}</strong>
            <span class:exact={match.distance === 0}>
              {distanceLabel(match.distance)} · 距离 {match.distance}
            </span>
          </div>
        </article>
      {/each}
    </div>
  {/if}
</div>

<style>
  .tool-page {
    min-height: 100%;
    padding: 24px 28px 32px;
  }

  .intro-card {
    display: flex;
    align-items: center;
    justify-content: space-between;
    gap: 24px;
    padding: 20px;
    border: 1px solid var(--border);
    border-radius: var(--radius-m);
    background: var(--surface);
    box-shadow: var(--shadow-1);
  }

  .intro-card h3 {
    font-size: var(--font-lg);
  }

  .intro-card p {
    margin-top: 4px;
    color: var(--text-2);
    font-size: var(--font-md);
  }

  .query-row {
    display: flex;
    gap: 12px;
    min-width: 0;
    padding: 16px 2px 12px;
    color: var(--text-3);
    font-size: var(--font-sm);
  }

  .query-row strong {
    overflow: hidden;
    color: var(--text-2);
    font-weight: 500;
    text-overflow: ellipsis;
    white-space: nowrap;
  }

  .message {
    margin-top: 18px;
    padding: 12px 14px;
    border-radius: var(--radius-s);
    font-size: var(--font-md);
  }

  .message.error {
    background: var(--danger-soft);
    color: var(--danger);
  }

  .empty-result {
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 4px;
    margin-top: 40px;
    color: var(--text-3);
    font-size: var(--font-md);
  }

  .empty-result strong {
    color: var(--text-2);
    font-size: var(--font-lg);
  }

  .result-heading {
    display: flex;
    align-items: baseline;
    gap: 8px;
    margin: 10px 2px 12px;
  }

  .result-heading span {
    color: var(--text-3);
    font-size: var(--font-sm);
  }

  .results-grid {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(150px, 1fr));
    gap: 14px;
  }

  .result-card {
    min-width: 0;
    overflow: hidden;
    border: 1px solid var(--border);
    border-radius: var(--radius-m);
    background: var(--surface);
    box-shadow: var(--shadow-1);
  }

  .thumbnail {
    aspect-ratio: 1;
    background: var(--surface-2);
  }

  .thumbnail :global(.thumbnail-stack),
  .thumbnail :global(img) {
    width: 100%;
    height: 100%;
  }

  .thumbnail :global(img) {
    object-fit: cover;
  }

  .card-info {
    display: flex;
    flex-direction: column;
    gap: 2px;
    padding: 9px 10px 10px;
  }

  .card-info strong {
    overflow: hidden;
    font-size: var(--font-sm);
    font-weight: 600;
    text-overflow: ellipsis;
    white-space: nowrap;
  }

  .card-info span {
    color: var(--text-3);
    font-size: var(--font-xs);
  }

  .card-info span.exact {
    color: var(--success);
  }
</style>

// src/react/views/tools/ImageSearchTool.tsx
import { useRef, useState } from "react";
import { open } from "@tauri-apps/plugin-dialog";
import { ImageUp } from "lucide-react";
import { getRowsByIds, searchSimilarImages, type RowRecord, type SimilarImageMatch } from "../../../lib/api";
import { errorText, formatCount } from "../../../lib/utils/format";
import { openRowInMainWindow } from "../../../lib/windows/toolbox";
import { useNativeDrop } from "../../state/tools/use-native-drop";
import { notify } from "../../state/notices";
import { runTask, useTasks } from "../../state/tasks";
import { Thumbnail } from "../../ui/Thumbnail";
import { Button } from "../../ui/controls";
import { ToolCard, ToolError, ToolPage, fileName } from "./shared";
const extensions = ["png", "jpg", "jpeg", "bmp", "gif", "webp", "tif", "tiff"];
export default function ImageSearchTool({ active }: { active: boolean }) {
  const [path, setPath] = useState<string | null>(null), [matches, setMatches] = useState<SimilarImageMatch[]>([]), [rows, setRows] = useState<Map<number, RowRecord>>(new Map()), [searching, setSearching] = useState(false), [searched, setSearched] = useState(false), [error, setError] = useState<string | null>(null), [opening, setOpening] = useState<number | null>(null);
  const zone = useRef<HTMLDivElement>(null), pending = useRef(false), busy = useTasks(state => state.busy);
  async function search(value: string) {
    if (pending.current || busy) return; pending.current = true; setPath(value); setMatches([]); setRows(new Map()); setSearched(false); setSearching(true); setError(null);
    try { await runTask("搜索相似图片", async () => { const result = await searchSimilarImages(value, 10); const records = result.length ? await getRowsByIds(result.map(item => item.rowId)) : []; setMatches(result); setRows(new Map(records.map(row => [row.id, row]))); setSearched(true); }); }
    catch (cause) { setError(errorText(cause)); } finally { pending.current = false; setSearching(false); }
  }
  const dragging = useNativeDrop(active, busy || searching, zone, async paths => { if (paths.length !== 1 || !extensions.includes(paths[0].split(".").pop()?.toLowerCase() ?? "")) { setError(paths.length > 1 ? "请一次只拖入一张参考图片。" : "请拖入支持的图片文件（PNG、JPG、BMP、GIF、WebP 或 TIFF）。"); return; } await search(paths[0]); }, setError);
  async function choose() { try { const value = await open({ multiple: false, directory: false, title: "选择用于搜索的图片", filters: [{ name: "图片", extensions }] }); if (typeof value === "string") await search(value); } catch (cause) { setError(errorText(cause)); } }
  return <ToolPage><div ref={zone} className={dragging ? "rt-drop is-dragging" : "rt-drop"}><ToolCard className="rt-row"><ImageUp size={26} /><div><h3>{dragging ? "松开即可开始搜索" : "选择或拖入一张参考图片"}</h3><p>工具会计算参考图的感知哈希，并返回距离不超过 10 的库内图片。</p><small>支持 PNG、JPG、BMP、GIF、WebP 和 TIFF</small></div><Button variant="primary" disabled={busy || searching} onClick={() => void choose()}>{searching ? "搜索中…" : path ? "换一张图片" : "选择图片…"}</Button></ToolCard></div>{path && <p title={path}>参考图片　{fileName(path)}</p>}<ToolError error={error} />{searching ? <div className="rt-empty" role="status">正在搜索相似图片…</div> : searched && !matches.length ? <div className="rt-empty"><strong>没有找到相似图片</strong><p>可以先到“资料库维护”刷新感知哈希后再试。</p></div> : matches.length > 0 && <><h3>搜索结果 · {formatCount(matches.length)} 张</h3><div className="rt-image-grid">{matches.map(match => { const row = rows.get(match.rowId); const name = fileName(row?.imagePath ?? row?.storedImagePath ?? `图片 #${match.rowId}`); return <button className="rt-image-result" title="在主窗口画廊中定位" key={match.rowId} disabled={opening !== null} onClick={() => { setOpening(match.rowId); void openRowInMainWindow(match.rowId).catch(cause => notify(`无法在主窗口打开图片：${errorText(cause)}`, "error")).finally(() => setOpening(null)); }}><Thumbnail rowId={match.rowId} alt={name} /><strong title={name}>{name}</strong><small>{opening === match.rowId ? "正在主窗口中打开…" : `${match.distance === 0 ? "完全匹配" : match.distance <= 3 ? "极高相似" : match.distance <= 6 ? "高度相似" : "可能相似"} · 距离 ${match.distance}`}</small></button>; })}</div></>}</ToolPage>;
}
