// src/lib/ui/WindowControls.svelte
<script lang="ts">
  import Copy from "@lucide/svelte/icons/copy";
  import Minus from "@lucide/svelte/icons/minus";
  import Square from "@lucide/svelte/icons/square";
  import X from "@lucide/svelte/icons/x";
  import { getCurrentWindow } from "@tauri-apps/api/window";

  const appWindow = getCurrentWindow();

  let maximized = $state(false);

  $effect(() => {
    let cancelled = false;
    let unlisten: (() => void) | null = null;
    const sync = (): void => {
      void appWindow.isMaximized().then(value => {
        if (!cancelled) {
          maximized = value;
        }
      });
    };
    sync();
    void appWindow.onResized(sync).then(fn => {
      if (cancelled) {
        fn();
      } else {
        unlisten = fn;
      }
    });
    return () => {
      cancelled = true;
      unlisten?.();
    };
  });
</script>

<div class="window-controls">
  <button type="button" title="最小化" aria-label="最小化" onclick={() => void appWindow.minimize()}>
    <span class="window-icon" aria-hidden="true">
      <Minus size={13} strokeWidth={1.5} />
    </span>
  </button>
  <button
    type="button"
    title={maximized ? "还原" : "最大化"}
    aria-label={maximized ? "还原" : "最大化"}
    onclick={() => void appWindow.toggleMaximize()}
  >
    <span class="window-icon" aria-hidden="true">
      {#if maximized}
        <Copy size={13} strokeWidth={1.5} />
      {:else}
        <Square size={13} strokeWidth={1.5} />
      {/if}
    </span>
  </button>
  <button type="button" class="close" title="关闭" aria-label="关闭" onclick={() => void appWindow.close()}>
    <span class="window-icon" aria-hidden="true">
      <X size={13} strokeWidth={1.5} />
    </span>
  </button>
</div>

<style>
  .window-controls {
    display: flex;
    align-self: stretch;
    flex: none;
  }

  .window-controls button {
    width: 44px;
    border: none;
    background: transparent;
    display: flex;
    align-items: center;
    justify-content: center;
    color: var(--text-2);
    padding: 0;
    border-radius: 0;
    transition:
      background var(--motion-fast) var(--ease-responsive),
      color var(--motion-fast) var(--ease-responsive);
  }

  .window-controls button:hover {
    background: var(--hover-wash);
    color: var(--text);
  }

  .window-controls button.close:hover {
    background: var(--close-hover);
    color: var(--on-accent);
  }

  .window-icon {
    width: 14px;
    height: 14px;
    display: flex;
    align-items: center;
    justify-content: center;
    transition: transform var(--motion-press) var(--ease-responsive);
  }

  .window-controls button:active .window-icon {
    transform: translateY(1px);
  }
</style>

// src/react/ui/WindowControls.tsx
import { useEffect, useState } from "react";
import { getCurrentWindow } from "@tauri-apps/api/window";
import { Copy, Minus, Square, X } from "lucide-react";
import { notify } from "../state/notices";
import { errorText } from "../../lib/utils/format";

export function WindowControls() {
  const [maximized, setMaximized] = useState(false);
  useEffect(() => {
    let disposed = false;
    let stop: (() => void) | undefined;
    const appWindow = getCurrentWindow();
    const sync = () => { void appWindow.isMaximized().then(value => { if (!disposed) setMaximized(value); }).catch(() => {}); };
    sync();
    void appWindow.onResized(sync).then(unlisten => { if (disposed) unlisten(); else stop = unlisten; }).catch(() => {});
    return () => { disposed = true; stop?.(); };
  }, []);
  const run = (action: "minimize" | "toggleMaximize" | "close") => {
    void getCurrentWindow()[action]().catch(error => notify(errorText(error), "error"));
  };
  return <div className="r-window-controls">
    <button type="button" aria-label="最小化" title="最小化" onClick={() => run("minimize")}><Minus size={13} strokeWidth={1.5} /></button>
    <button type="button" aria-label={maximized ? "还原" : "最大化"} title={maximized ? "还原" : "最大化"} onClick={() => run("toggleMaximize")}>{maximized ? <Copy size={13} strokeWidth={1.5} /> : <Square size={13} strokeWidth={1.5} />}</button>
    <button type="button" className="close" aria-label="关闭" title="关闭" onClick={() => run("close")}><X size={13} strokeWidth={1.5} /></button>
  </div>;
}
