// src/react/views/TopBar.tsx
import { useEffect, useRef, useState } from "react";
import { ArrowLeft, ArrowRight, X } from "lucide-react";
import { useWorkspace } from "../state/workspace";
import { setQuery, useLibrary, useRows } from "../state/library";
import { formatCount } from "../../lib/utils/format";
import { Button, Hint, Menu } from "../ui/controls";
import { WindowControls } from "../ui/WindowControls";
import { navigateHistory, useNavigation } from "../state/navigation";
import { buildExportItems } from "../state/export-actions";
import { chooseImageArchive, chooseImageFolder, updateAutoArtistPrefixOnImport } from "../state/import-actions";
import { useTasks } from "../state/tasks";
import { useSelection } from "../state/selection";
import { setMaterialSearch, useMaterials } from "../state/materials";

export function TopBar({ onUpdateImport, onToolbox }: { onUpdateImport: () => void; onToolbox: () => void }) {
  const view = useWorkspace(state => state.viewMode);
  const total = useLibrary(state => state.snapshot?.library?.rowCount ?? 0);
  const autoArtistPrefix = useLibrary(state => state.snapshot?.autoArtistPrefixOnImport ?? false);
  const busy = useTasks(state => state.busy);
  useSelection();
  const rowSearch = useRows(state => state.query.search);
  const materialSearch = useMaterials(state => state.search);
  const materialMode = view === "materials";
  const search = materialMode ? materialSearch : rowSearch;
  const navigation = useNavigation();
  const searchSession = useRef(0);
  const lastInput = useRef(0);
  const [input, setInput] = useState(search);
  const searchTimer = useRef<ReturnType<typeof setTimeout> | undefined>(undefined);
  const composing = useRef(false);
  useEffect(() => { clearTimeout(searchTimer.current); setInput(search); }, [search, navigation.token, materialMode]);
  useEffect(() => () => clearTimeout(searchTimer.current), []);
  const applySearch = (value: string) => { if (materialMode) setMaterialSearch(value); else setQuery({ search: value }, searchSession.current); };
  const commit = (value: string) => { clearTimeout(searchTimer.current); applySearch(value); searchSession.current++; };
  const schedule = (value: string) => {
    if (Date.now() - lastInput.current > 1500) searchSession.current++;
    lastInput.current = Date.now();
    clearTimeout(searchTimer.current); searchTimer.current = setTimeout(() => applySearch(value), 300);
  };
  return <header className="r-topbar" data-tauri-drag-region>
    <div className="r-brand" data-tauri-drag-region><span data-tauri-drag-region>智能表格</span><small>{formatCount(total)} 张图片</small></div>
    <div className="r-history" role="group" aria-label="浏览历史">
      <Hint text={navigation.back ? `后退到 ${navigation.back}` : "没有可后退的浏览记录"}><Button variant="ghost" size="icon" disabled={!navigation.back || navigation.restoring} aria-label="后退" onClick={() => void navigateHistory(-1)}><ArrowLeft size={15} /></Button></Hint>
      <Hint text={navigation.forward ? `前进到 ${navigation.forward}` : "没有可前进的浏览记录"}><Button variant="ghost" size="icon" disabled={!navigation.forward || navigation.restoring} aria-label="前进" onClick={() => void navigateHistory(1)}><ArrowRight size={15} /></Button></Hint>
    </div>
    <div className="r-title-spacer" data-tauri-drag-region />
    {view !== "promptDocs" && <div className="r-search"><input type="text" placeholder={materialMode ? "搜索素材名称 / 文本内容…" : "搜索文件名 / 提示词 / 画师…"} aria-label={materialMode ? "搜索素材名称和文本" : "搜索文件名、提示词和画师"} value={input}
      onChange={event => { setInput(event.target.value); if (!composing.current) schedule(event.target.value); }}
      onCompositionStart={() => { composing.current = true; clearTimeout(searchTimer.current); }}
      onCompositionEnd={event => { composing.current = false; schedule(event.currentTarget.value); }}
      onBlur={() => { if (!composing.current) commit(input); }}
      onKeyDown={event => { if (event.key === "Enter" && !event.nativeEvent.isComposing) commit(input); }} />
      {input && <Button variant="ghost" size="icon" className="r-search-clear" aria-label="清除搜索" onClick={() => { setInput(""); commit(""); }}><X size={13} /></Button>}
    </div>}
    <div className="r-top-actions"><Button variant="ghost" disabled={busy} onClick={onToolbox}>工具箱</Button>
      {!materialMode && <><Menu label="导入" disabled={busy} items={[{ label: "导入文件夹", action: () => void chooseImageFolder() }, { label: "导入压缩包", hint: "zip / 7z / rar", action: () => void chooseImageArchive() },
        { label: "导入时自动补全画师前缀", hint: "仅使用库内明确 artist: 证据", checked: autoArtistPrefix, action: () => void updateAutoArtistPrefixOnImport(!autoArtistPrefix) },
        { label: "更新现有图片", hint: "只更新，不新增；保留 Tag / 分组", separator: true, action: onUpdateImport }]} />
      <Menu label="导出" variant="primary" disabled={!total || busy} items={buildExportItems()} /></>}
    </div><WindowControls />
  </header>;
}

// src/lib/views/shell/TopBar.svelte
<script lang="ts">
  import X from "@lucide/svelte/icons/x";
  import { onDestroy, untrack } from "svelte";
  import NavigationButtons from "./NavigationButtons.svelte";
  import { navigation } from "../../stores/navigation.svelte";

  import { app, errorText, formatCount, setNotice } from "../../stores/app-state.svelte";
  import {
    chooseImageArchive,
    chooseImageFolder,
    updateAutoArtistPrefixOnImport,
  } from "../../stores/import-actions.svelte";
  import { buildExportItems } from "../../stores/export-actions";
  import { clearSelection } from "../../stores/selection-store.svelte";
  import { rowStore, setSearch } from "../../stores/row-store.svelte";
  import { materialBrowser } from "../../stores/material-browser.svelte";
  import Dropdown, { type DropdownItem } from "../../ui/Dropdown.svelte";
  import { openToolboxWindow } from "../../windows/toolbox";
  import ViewSwitcher from "./ViewSwitcher.svelte";
  import WindowControls from "../../ui/WindowControls.svelte";
  import { softPop } from "../../ui/motion";

  let searchInput = $state("");
  let debounceTimer: ReturnType<typeof setTimeout> | undefined;
  let searchSession = 0;
  let lastInputAt = 0;
  let searchScope: "materials" | "rows" = "rows";
  const isMaterials = $derived(app.viewMode === "materials");

  function flushSearch(): void {
    clearTimeout(debounceTimer);
    if ((isMaterials ? "materials" : "rows") !== searchScope) return;
    if (isMaterials) { materialBrowser.search = searchInput; return; }
    if (rowStore.search !== searchInput) {
      setSearch(searchInput, searchSession);
      clearSelection();
    }
  }

  function finishSearch(): void {
    flushSearch();
    searchSession += 1;
  }

  onDestroy(() => clearTimeout(debounceTimer));

  function onSearchInput(event: Event): void {
    const value = (event.target as HTMLInputElement).value;
    searchInput = value;
    searchScope = isMaterials ? "materials" : "rows";
    clearTimeout(debounceTimer);
    if (event instanceof InputEvent && event.isComposing) return;
    if (Date.now() - lastInputAt > 1500) searchSession += 1;
    lastInputAt = Date.now();
    debounceTimer = setTimeout(flushSearch, 300);
  }

  function clearSearch(): void {
    searchSession += 1;
    searchInput = "";
    clearTimeout(debounceTimer);
    if (isMaterials) { materialBrowser.search = ""; return; }
    if (rowStore.search !== "") {
      setSearch("");
      clearSelection();
    }
  }

  // Each library owns its search; switching views cancels any uncommitted debounce.
  $effect(() => {
    const scope = isMaterials ? "materials" : "rows";
    const external = isMaterials ? materialBrowser.search : rowStore.search;
    void navigation.token;
    untrack(() => {
      searchInput = external;
      searchScope = scope;
      clearTimeout(debounceTimer);
    });
  });

  const library = $derived(app.snapshot?.library ?? null);

  const importItems = $derived<DropdownItem[]>([
    { label: "导入文件夹", action: () => void chooseImageFolder() },
    { label: "导入压缩包", hint: "zip / 7z / rar", action: () => void chooseImageArchive() },
    {
      label: "导入时自动补全画师前缀",
      hint: "仅使用库内明确 artist: 证据",
      checked: app.snapshot?.autoArtistPrefixOnImport ?? false,
      action: () => void updateAutoArtistPrefixOnImport(
        !(app.snapshot?.autoArtistPrefixOnImport ?? false),
      ),
    },
    {
      label: "更新现有图片",
      hint: "只更新，不新增；保留 Tag / 分组",
      action: () => (app.updateImportOpen = true),
    },
  ]);

  const exportItems = $derived<DropdownItem[]>(buildExportItems());

  const exportDisabled = $derived(app.busy || !library || library.rowCount === 0);

  async function openToolbox(): Promise<void> {
    try {
      await openToolboxWindow();
    } catch (error) {
      setNotice({ tone: "error", text: errorText(error) });
    }
  }
</script>

<header class="topbar" data-tauri-drag-region>
  <div class="brand" data-tauri-drag-region>
    <span data-tauri-drag-region>智能表格</span>
    {#if library && library.rowCount > 0}
      <small data-tauri-drag-region>{formatCount(library.rowCount)} 张图片</small>
    {/if}
  </div>

  <NavigationButtons />
  <ViewSwitcher />

  <div class="title-spacer" data-tauri-drag-region></div>

  {#if app.viewMode !== "promptDocs"}
    <div class="search-box" data-tauri-drag-region>
      <input
        type="text"
        placeholder={isMaterials ? "搜索素材名称 / 文本内容…" : "搜索文件名 / 提示词 / 画师…"}
        aria-label={isMaterials ? "搜索素材名称和文本" : "搜索文件名、提示词和画师"}
        value={searchInput}
        oninput={onSearchInput}
        oncompositionend={onSearchInput}
        onblur={finishSearch}
        onkeydown={event => { if (event.key === "Enter" && !event.isComposing) finishSearch(); }}
        class:has-value={searchInput.length > 0}
      />
      {#if searchInput.length > 0}
        <button
          type="button"
          class="search-clear"
          onclick={clearSearch}
          title="清除搜索"
          transition:softPop={{ duration: 110, y: 0, start: 0.85 }}
        ><X size={13} strokeWidth={2} /></button>
      {/if}
    </div>
  {/if}

  <div class="actions">
    <button
      type="button"
      class="btn btn-ghost"
      disabled={app.busy}
      onclick={() => void openToolbox()}
    >
      工具箱
    </button>
    {#if app.viewMode !== "materials"}
      <Dropdown label="导入" items={importItems} disabled={app.busy} ghost />
      <Dropdown label="导出" items={exportItems} disabled={exportDisabled} primary />
    {/if}
  </div>
  <WindowControls />
</header>

<style>
  .topbar {
    display: flex;
    align-items: center;
    gap: 12px;
    height: 52px;
    padding: 0 0 0 20px;
    background: var(--surface);
    border-bottom: 1px solid var(--border);
    flex: none;
    min-width: 0;
  }

  .brand {
    display: flex;
    align-items: baseline;
    gap: 7px;
    flex: none;
    font-size: var(--font-lg);
    font-weight: 700;
    letter-spacing: -0.01em;
    color: var(--text);
    white-space: nowrap;
  }

  .brand small {
    font-size: var(--font-xs);
    font-weight: 400;
    color: var(--text-3);
    letter-spacing: 0;
    font-variant-numeric: tabular-nums;
  }

  /* 窄窗口：先隐藏品牌小字，给控件让位 */
  @media (max-width: 1180px) {
    .brand small {
      display: none;
    }
  }

  @media (max-width: 1040px) {
    .topbar {
      gap: 8px;
    }
  }

  @media (max-width: 950px) {
    .brand { display: none; }
    .topbar { padding-left: 10px; gap: 6px; }
    .title-spacer { min-width: 0; }
  }

  .title-spacer {
    flex: 1;
    min-width: 16px;
  }

  .search-box {
    position: relative;
    flex: 0 1 260px;
    min-width: 120px;
  }

  .search-box input {
    width: 100%;
    height: 32px;
    padding: 0 30px 0 14px;
    border: 1px solid transparent;
    border-radius: var(--radius-full);
    background: var(--surface-2);
    font-size: var(--font-sm);
    color: var(--text);
    outline: none;
    box-sizing: border-box;
    transition:
      border-color var(--motion-fast) var(--ease-responsive),
      box-shadow var(--motion-fast) var(--ease-responsive),
      background var(--motion-fast) var(--ease-responsive);
  }

  .search-box input:hover:not(:focus) {
    background: var(--surface-3);
  }

  .search-box input:focus {
    border-color: var(--accent);
    background: var(--surface);
    box-shadow: var(--focus-ring);
  }

  .search-box input::placeholder {
    color: var(--text-3);
  }

  .search-clear {
    position: absolute;
    right: 5px;
    top: 50%;
    transform: translateY(-50%);
    display: flex;
    align-items: center;
    justify-content: center;
    min-width: 24px;
    min-height: 24px;
    border: none;
    background: transparent;
    color: var(--text-3);
    line-height: 1;
    padding: 0;
    cursor: pointer;
    border-radius: 50%;
  }

  .search-clear:hover {
    background: var(--surface-3);
    color: var(--text);
  }

  .search-clear:active {
    transform: translateY(-50%) scale(0.85);
  }

  .actions {
    display: flex;
    gap: 4px;
    flex: none;
    margin-right: 4px;
  }

  /* 超窄窗口：按钮收紧内距 */
  @media (max-width: 1000px) {
    .actions :global(.btn) {
      padding-left: 10px;
      padding-right: 10px;
    }

    .search-box {
      flex-basis: 180px;
    }
  }

  @media (max-width: 950px) {
    .title-spacer { min-width: 0; }
  }

  @media (max-width: 850px) {
    .topbar { gap: 4px; padding-left: 6px; }
    .actions :global(.btn) { padding-left: 6px; padding-right: 6px; }
  }
</style>
