// src/react/views/prompt-docs/PromptDocsView.tsx
import { useEffect, useRef, useState } from "react";
import { Editor } from "@tiptap/core";
import FileHandler from "@tiptap/extension-file-handler";
import Image from "@tiptap/extension-image";
import StarterKit from "@tiptap/starter-kit";
import { open } from "@tauri-apps/plugin-dialog";
import { Bold, Check, Copy, FileText, ImagePlus, Italic, List, LoaderCircle, Plus, Redo2, RotateCw, Trash2, Undo2 } from "lucide-react";
import { importPromptDocImageBytes, importPromptDocImageFromPath } from "../../../lib/api/prompt-docs";
import { errorText } from "../../../lib/utils/format";
import { Button, Input, Modal } from "../../ui/controls";
import { notify } from "../../state/notices";
import { runTask, useTasks } from "../../state/tasks";
import { useLibrary } from "../../state/library";
import { editPromptDoc, flushPromptDocSave, initializePromptDocs, registerPromptDocAsset, removeActivePromptDoc, switchPromptDoc, usePromptDocs } from "../../state/prompt-docs";
import "./prompt-docs.css";

const extensions = ["png", "jpg", "jpeg", "webp", "gif", "bmp", "tif", "tiff"];
const mimeTypes = ["image/png", "image/jpeg", "image/webp", "image/gif", "image/bmp", "image/tiff"];

export function PromptDocsView() {
  const state = usePromptDocs();
  const busy = useTasks(store => store.busy);
  const directory = useLibrary(store => store.snapshot?.dataDirectory);
  const host = useRef<HTMLDivElement>(null);
  const editorRef = useRef<Editor | null>(null);
  const [, renderSelection] = useState(0);
  const [deleteOpen, setDeleteOpen] = useState(false);
  const [discardOpen, setDiscardOpen] = useState(false);
  const discardResolver = useRef<((answer: boolean) => void) | null>(null);
  const [copied, setCopied] = useState(false);
  const copyTimer = useRef<ReturnType<typeof setTimeout> | undefined>(undefined);
  const mounted = useRef(false);
  const locked = state.loading || busy || state.directory !== (directory ?? null);

  async function importImages(files: File[] | string[], position?: number): Promise<void> {
    const current = usePromptDocs.getState();
    if (current.loading || useTasks.getState().busy) return;
    if (!current.active) { notify("请先创建或选择一个提示词文档。", "error"); return; }
    const accepted = files.filter(file => typeof file === "string"
      ? extensions.includes(file.split(".").pop()?.toLowerCase() ?? "") : mimeTypes.includes(file.type));
    if (!accepted.length) return;
    const id = current.active.id;
    const editor = editorRef.current;
    if (!editor) return;
    usePromptDocs.setState({ loading: true });
    try {
      await runTask("插入文档图片", async () => {
        let nextPosition = position;
        for (const file of accepted) {
          const asset = typeof file === "string" ? await importPromptDocImageFromPath(id, file)
            : await importPromptDocImageBytes(id, file.name || "clipboard.png", Array.from(new Uint8Array(await file.arrayBuffer())));
          if (usePromptDocs.getState().active?.id !== id) break;
          const src = registerPromptDocAsset(asset);
          // The view may have unmounted while an image was importing. Preserve
          // the imported image in the draft without touching a destroyed editor.
          if (!editor.isDestroyed) {
            if (typeof nextPosition === "number") {
              const safePosition = Math.max(0, Math.min(nextPosition, editor.state.doc.content.size));
              editor.chain().focus().insertContentAt(safePosition, { type: "image", attrs: { src } }).run();
              nextPosition = safePosition + 1;
            } else editor.chain().focus().setImage({ src }).run();
          } else {
            const draft = usePromptDocs.getState();
            editPromptDoc({ content: { ...draft.content, content: [...draft.content.content ?? [], { type: "image", attrs: { src } }] } });
            usePromptDocs.setState(store => ({ documentVersion: store.documentVersion + 1 }));
          }
        }
      });
    } catch (error) { notify(`插入图片失败：${errorText(error)}`, "error"); }
    finally { usePromptDocs.setState({ loading: false }); }
  }

  useEffect(() => {
    mounted.current = true;
    const current = usePromptDocs.getState();
    const editor = new Editor({
      element: host.current!, editable: Boolean(current.active) && !current.loading,
      content: current.content,
      extensions: [
        StarterKit.configure({ heading: { levels: [1, 2, 3] } }),
        Image.configure({ allowBase64: false, resize: { enabled: true, minWidth: 80, minHeight: 80, alwaysPreserveAspectRatio: true } }),
        FileHandler.configure({ allowedMimeTypes: mimeTypes,
          onPaste: (_editor, files) => { void importImages(files); },
          onDrop: (_editor, files, position) => { void importImages(files, position); },
        }),
      ],
      editorProps: { attributes: { "aria-label": "提示词文档正文", role: "textbox", "aria-multiline": "true" } },
      onUpdate: ({ editor: instance }) => {
        editPromptDoc({ content: instance.getJSON(), plainText: instance.getText({ blockSeparator: "\n" }) });
        renderSelection(value => value + 1);
      },
      onSelectionUpdate: () => renderSelection(value => value + 1),
    });
    editorRef.current = editor;
    const pathDrop = (event: Event) => { const paths = (event as CustomEvent<string[]>).detail; if (Array.isArray(paths)) void importImages(paths); };
    window.addEventListener("prompt-doc-path-drop", pathDrop);
    return () => {
      mounted.current = false;
      discardResolver.current?.(false);
      discardResolver.current = null;
      window.removeEventListener("prompt-doc-path-drop", pathDrop);
      clearTimeout(copyTimer.current);
      void flushPromptDocSave();
      editor.destroy();
      editorRef.current = null;
    };
  }, [state.documentVersion]);

  useEffect(() => { void initializePromptDocs(); }, [directory]);
  useEffect(() => { editorRef.current?.setEditable(Boolean(state.active) && !locked, false); }, [state.active?.id, locked]);

  const confirmDiscard = () => new Promise<boolean>(resolve => { discardResolver.current = resolve; setDiscardOpen(true); });
  const resolveDiscard = (answer: boolean) => { setDiscardOpen(false); discardResolver.current?.(answer); discardResolver.current = null; };
  async function chooseImages(): Promise<void> {
    try {
      const result = await open({ multiple: true, directory: false, title: "选择要插入的图片", filters: [{ name: "图片", extensions }] });
      if (result) await importImages(Array.isArray(result) ? result : [result]);
    } catch (error) { notify(errorText(error), "error"); }
  }
  async function copy(): Promise<void> {
    try {
      await navigator.clipboard.writeText(editorRef.current?.getText({ blockSeparator: "\n" }) ?? state.plainText);
      if (mounted.current) { setCopied(true); clearTimeout(copyTimer.current); copyTimer.current = setTimeout(() => setCopied(false), 1800); }
      notify("提示词文本已复制。");
    } catch (error) { notify(`复制失败：${errorText(error)}`, "error"); }
  }
  const keyword = state.search.trim().toLocaleLowerCase();
  const docs = state.docs.filter(doc => !keyword || `${doc.title}\n${doc.plainText}`.toLocaleLowerCase().includes(keyword));
  const editor = editorRef.current;
  const status = !state.active ? "" : state.saveState === "saving" ? "保存中…" : state.saveState === "dirty" ? "有未保存修改" : state.saveState === "error" ? "保存失败" : "已保存";

  return <section className="r-prompt-docs" aria-label="提示词文档">
    <aside className="r-pd-list">
      <header><h2>提示词文档</h2><Button variant="primary" disabled={locked} onClick={() => void switchPromptDoc(null, confirmDiscard)}><Plus size={14} />新建</Button></header>
      <Input aria-label="搜索提示词文档" placeholder="搜索标题和正文…" value={state.search} onChange={event => usePromptDocs.setState({ search: event.target.value })} />
      <div className="r-pd-items" aria-label="文档列表">
        {state.error && <div className="r-pd-error" role="alert"><p>{state.error}</p><Button disabled={locked} onClick={() => void initializePromptDocs()}><RotateCw size={14} />重新加载</Button></div>}
        {!state.error && !docs.length && <p className="r-pd-list-empty">{state.loading ? "正在加载文档…" : keyword ? "没有匹配的文档" : "还没有提示词文档"}</p>}
        {docs.map(doc => <button key={doc.id} type="button" className={`r-pd-item ${state.active?.id === doc.id ? "is-active" : ""}`} aria-current={state.active?.id === doc.id ? "page" : undefined} disabled={locked} onClick={() => void switchPromptDoc(doc.id, confirmDiscard)}>
          <span className="r-pd-name" title={doc.title}>{doc.title}</span><time>{doc.updatedAt}</time>{doc.plainText.trim() && <span className="r-pd-snippet">{doc.plainText}</span>}
        </button>)}
      </div>
    </aside>
    <main className="r-pd-editor" aria-busy={state.loading}>
      {state.loading && <div className="r-pd-progress" />}
      <div className="r-pd-titlebar">
        <Input className="r-pd-title" aria-label="文档标题" value={state.title} placeholder="未命名文档" disabled={!state.active || locked} onChange={event => editPromptDoc({ title: event.target.value })} />
        <span className={`r-pd-status ${state.saveState === "error" ? "is-error" : ""}`} role="status">{state.saveState === "saving" ? <LoaderCircle className="r-pd-spin" size={12} /> : state.saveState === "saved" ? <Check size={12} /> : null}{status}</span>
        {state.saveState === "error" && <Button size="sm" onClick={() => void flushPromptDocSave()} disabled={locked}>重试保存</Button>}
        <Button disabled={!state.active || locked} onClick={() => void copy()} title="复制全文纯文本" aria-label="复制全文纯文本">{copied ? <Check size={14} /> : <Copy size={14} />}<span className="r-pd-copy-label">复制全文纯文本</span></Button>
        <Button variant="danger" disabled={!state.active || locked} onClick={() => setDeleteOpen(true)} title="删除文档" aria-label="删除文档"><Trash2 size={14} /><span className="r-pd-delete-label">删除</span></Button>
      </div>
      <div className="r-pd-toolbar" role="toolbar" aria-label="提示词文档工具栏">
        <Button disabled={!state.active || locked} aria-pressed={editor?.isActive("paragraph") ?? false} onClick={() => editor?.chain().focus().setParagraph().run()}>正文</Button>
        <Button disabled={!state.active || locked} aria-pressed={editor?.isActive("heading", { level: 2 }) ?? false} onClick={() => editor?.chain().focus().toggleHeading({ level: 2 }).run()}>标题</Button>
        <Button disabled={!state.active || locked} aria-label="粗体" aria-pressed={editor?.isActive("bold") ?? false} onClick={() => editor?.chain().focus().toggleBold().run()}><Bold size={14} /></Button>
        <Button disabled={!state.active || locked} aria-label="斜体" aria-pressed={editor?.isActive("italic") ?? false} onClick={() => editor?.chain().focus().toggleItalic().run()}><Italic size={14} /></Button>
        <Button disabled={!state.active || locked} aria-pressed={editor?.isActive("bulletList") ?? false} onClick={() => editor?.chain().focus().toggleBulletList().run()}><List size={14} />列表</Button>
        <Button disabled={!state.active || locked} onClick={() => void chooseImages()}><ImagePlus size={14} />插入图片</Button>
        <span className="r-pd-toolbar-separator" />
        <Button aria-label="撤销文档编辑" disabled={!state.active || locked || !editor?.can().undo()} onClick={() => editor?.chain().focus().undo().run()}><Undo2 size={14} /></Button>
        <Button aria-label="重做文档编辑" disabled={!state.active || locked || !editor?.can().redo()} onClick={() => editor?.chain().focus().redo().run()}><Redo2 size={14} /></Button>
      </div>
      <div className="r-pd-shell"><div className={`r-pd-surface ${!state.active ? "is-disabled" : ""}`}>
        <div ref={host} className="r-pd-content" />
        {!state.active && <div className="r-pd-empty"><FileText size={30} /><h3>创建一个提示词文档</h3><p>整理提示词，插入图片，修改后自动保存。</p><Button variant="primary" disabled={locked} onClick={() => void switchPromptDoc(null, confirmDiscard)}><Plus size={14} />新建文档</Button></div>}
      </div></div>
    </main>
    <Modal open={deleteOpen} onClose={() => setDeleteOpen(false)} title="删除提示词文档" description={`将删除「${state.title || "未命名文档"}」及其中插入的图片，此操作不可撤销。`} busy={state.loading}
      footer={<><Button disabled={state.loading} onClick={() => setDeleteOpen(false)}>取消</Button><Button variant="danger" disabled={state.loading} onClick={() => { void removeActivePromptDoc().then(() => { if (mounted.current) setDeleteOpen(false); }); }}>确认删除</Button></>}><p>如需保留提示词，请先复制全文。</p></Modal>
    <Modal open={discardOpen} onClose={() => resolveDiscard(false)} title="当前文档保存失败" description="切换将丢失未保存的修改。你可以留在本文档重试保存。"
      footer={<><Button onClick={() => resolveDiscard(false)}>留在本文档</Button><Button variant="danger" onClick={() => resolveDiscard(true)}>放弃修改并切换</Button></>}><p>是否放弃当前修改？</p></Modal>
  </section>;
}

// src/lib/views/prompt-docs/PromptDocsView.svelte
<script lang="ts">
  import { convertFileSrc } from "@tauri-apps/api/core";
  import { confirm as confirmDialog, open } from "@tauri-apps/plugin-dialog";
  import { Editor, type JSONContent } from "@tiptap/core";
  import FileHandler from "@tiptap/extension-file-handler";
  import Image from "@tiptap/extension-image";
  import StarterKit from "@tiptap/starter-kit";
  import { onMount, tick } from "svelte";

  import {
    createPromptDoc,
    deletePromptDoc,
    importPromptDocImageBytes,
    importPromptDocImageFromPath,
    listPromptDocs,
    loadPromptDoc,
    savePromptDoc,
    type PromptDocAsset,
    type PromptDocDetail,
    type PromptDocSummary,
  } from "../../api";
  import { errorText, setNotice } from "../../stores/app-state.svelte";
  import { lastPromptDoc, rememberPromptDoc } from "../../stores/view-state";

  const IMAGE_MIME_TYPES = [
    "image/png",
    "image/jpeg",
    "image/webp",
    "image/gif",
    "image/bmp",
    "image/tiff",
  ];
  const IMAGE_EXTENSIONS = new Set(["png", "jpg", "jpeg", "webp", "gif", "bmp", "tif", "tiff"]);

  let docs = $state<PromptDocSummary[]>([]);
  let activeDoc = $state<PromptDocDetail | null>(null);
  let title = $state("");
  let search = $state("");
  let loading = $state(false);
  let saving = $state(false);
  let saveState = $state<"idle" | "dirty" | "saving" | "saved" | "error">("idle");
  let editorElement = $state<HTMLDivElement | null>(null);
  let editor = $state<Editor | null>(null);
  let editorVersion = $state(0);

  let saveTimer: ReturnType<typeof setTimeout> | undefined;
  let suppressUpdate = false;
  const displayToPersistent = new Map<string, string>();
  const persistentToDisplay = new Map<string, string>();

  const filteredDocs = $derived(
    docs.filter(doc => {
      const keyword = search.trim().toLowerCase();
      if (!keyword) return true;
      return (
        doc.title.toLowerCase().includes(keyword) ||
        doc.plainText.toLowerCase().includes(keyword)
      );
    }),
  );

  const statusText = $derived.by(() => {
    if (!activeDoc) return "";
    if (saving || saveState === "saving") return "保存中…";
    if (saveState === "dirty") return "有未保存修改";
    if (saveState === "error") return "保存失败";
    return "已保存";
  });

  onMount(() => {
    const pathDropHandler = (event: Event) => {
      const paths = (event as CustomEvent<string[]>).detail ?? [];
      void importImagePaths(paths);
    };

    window.addEventListener("prompt-doc-path-drop", pathDropHandler);
    void initialize();

    return () => {
      window.removeEventListener("prompt-doc-path-drop", pathDropHandler);
      window.clearTimeout(saveTimer);
      void flushSave();
      editor?.destroy();
    };
  });

  async function initialize(): Promise<void> {
    await tick();
    createEditor();
    await reloadDocs();
    // 优先恢复上次打开的文档，不存在（已删/换库）则回退第一篇
    const remembered = lastPromptDoc();
    const target = remembered && docs.some(doc => doc.id === remembered) ? remembered : docs[0]?.id;
    if (target) {
      await selectDoc(target);
    } else {
      clearEditor();
    }
  }

  function createEditor(): void {
    if (!editorElement || editor) return;
    editor = new Editor({
      element: editorElement,
      editable: false,
      content: emptyDocContent(),
      extensions: [
        StarterKit.configure({
          heading: { levels: [1, 2, 3] },
        }),
        Image.configure({
          allowBase64: false,
          resize: {
            enabled: true,
            minWidth: 80,
            minHeight: 80,
            alwaysPreserveAspectRatio: true,
          },
        }),
        FileHandler.configure({
          allowedMimeTypes: IMAGE_MIME_TYPES,
          onPaste: (_editor, files) => {
            void importImageFiles(files);
          },
          onDrop: (_editor, files, pos) => {
            void importImageFiles(files, pos);
          },
        }),
      ],
      onUpdate: () => {
        editorVersion += 1;
        if (!suppressUpdate) {
          scheduleSave();
        }
      },
      onSelectionUpdate: () => {
        editorVersion += 1;
      },
    });
  }

  async function reloadDocs(): Promise<void> {
    try {
      docs = await listPromptDocs();
    } catch (error) {
      setNotice({ tone: "error", text: errorText(error) });
    }
  }

  async function createNewDoc(): Promise<void> {
    await flushSave();
    loading = true;
    try {
      const detail = await createPromptDoc("未命名文档");
      upsertDocSummary(detail);
      applyDoc(detail);
    } catch (error) {
      setNotice({ tone: "error", text: errorText(error) });
    } finally {
      loading = false;
    }
  }

  async function selectDoc(docId: string): Promise<void> {
    if (activeDoc?.id === docId) return;
    await flushSave();
    loading = true;
    try {
      applyDoc(await loadPromptDoc(docId));
    } catch (error) {
      setNotice({ tone: "error", text: errorText(error) });
    } finally {
      loading = false;
    }
  }

  function applyDoc(detail: PromptDocDetail): void {
    activeDoc = detail;
    rememberPromptDoc(detail.id);
    title = detail.title;
    saveState = "saved";
    const content = toDisplayContent(detail.content, detail.assets);
    suppressUpdate = true;
    editor?.commands.setContent(content as JSONContent, { emitUpdate: false });
    editor?.setEditable(true);
    suppressUpdate = false;
    editorVersion += 1;
  }

  function clearEditor(): void {
    activeDoc = null;
    rememberPromptDoc(null);
    title = "";
    saveState = "idle";
    displayToPersistent.clear();
    persistentToDisplay.clear();
    suppressUpdate = true;
    editor?.commands.setContent(emptyDocContent(), { emitUpdate: false });
    editor?.setEditable(false);
    suppressUpdate = false;
    editorVersion += 1;
  }

  function onTitleInput(event: Event): void {
    title = (event.target as HTMLInputElement).value;
    scheduleSave();
  }

  function scheduleSave(): void {
    if (!activeDoc || !editor) return;
    saveState = "dirty";
    window.clearTimeout(saveTimer);
    saveTimer = window.setTimeout(() => {
      void flushSave();
    }, 800);
  }

  async function flushSave(): Promise<void> {
    window.clearTimeout(saveTimer);
    if (!activeDoc || !editor || saveState !== "dirty") return;

    saving = true;
    saveState = "saving";
    try {
      const content = toPersistentContent(editor.getJSON());
      const plainText = editor.getText({ blockSeparator: "\n" });
      const saved = await savePromptDoc(activeDoc.id, title, content, plainText);
      activeDoc = { ...saved, content };
      title = saved.title;
      upsertDocSummary(saved);
      saveState = "saved";
    } catch (error) {
      saveState = "error";
      setNotice({ tone: "error", text: errorText(error) });
    } finally {
      saving = false;
    }
  }

  async function deleteActiveDoc(): Promise<void> {
    if (!activeDoc) return;
    const docId = activeDoc.id;
    const confirmed = await confirmDialog(
      `将删除「${activeDoc.title}」及其中插入的图片。此操作不可撤销，是否继续？`,
      { title: "删除提示词文档", kind: "warning", okLabel: "确认删除", cancelLabel: "取消" },
    );
    if (!confirmed) return;

    loading = true;
    try {
      await deletePromptDoc(docId);
      docs = docs.filter(doc => doc.id !== docId);
      const next = docs[0];
      if (next) {
        activeDoc = null;
        await selectDoc(next.id);
      } else {
        clearEditor();
      }
      setNotice({ tone: "success", text: "提示词文档已删除。" });
    } catch (error) {
      setNotice({ tone: "error", text: errorText(error) });
    } finally {
      loading = false;
    }
  }

  async function chooseImageFiles(): Promise<void> {
    if (!activeDoc) {
      setNotice({ tone: "error", text: "请先创建或选择一个提示词文档。" });
      return;
    }
    const selection = await open({
      multiple: true,
      directory: false,
      title: "选择要插入的图片",
      filters: [{ name: "图片", extensions: Array.from(IMAGE_EXTENSIONS) }],
    });
    if (typeof selection === "string") {
      await importImagePaths([selection]);
    } else if (Array.isArray(selection)) {
      await importImagePaths(selection);
    }
  }

  async function importImagePaths(paths: string[]): Promise<void> {
    if (!activeDoc || !editor) {
      if (paths.length > 0) {
        setNotice({ tone: "error", text: "请先创建或选择一个提示词文档。" });
      }
      return;
    }
    const imagePaths = paths.filter(isImagePath);
    if (imagePaths.length === 0) return;

    loading = true;
    try {
      for (const path of imagePaths) {
        const asset = await importPromptDocImageFromPath(activeDoc.id, path);
        insertImage(registerAsset(asset));
      }
      scheduleSave();
    } catch (error) {
      setNotice({ tone: "error", text: errorText(error) });
    } finally {
      loading = false;
    }
  }

  async function importImageFiles(files: File[], position?: number): Promise<void> {
    if (!activeDoc || !editor) return;
    const images = files.filter(file => file.type.startsWith("image/"));
    if (images.length === 0) return;

    loading = true;
    try {
      let insertPosition = position;
      for (const file of images) {
        const bytes = Array.from(new Uint8Array(await file.arrayBuffer()));
        const asset = await importPromptDocImageBytes(
          activeDoc.id,
          file.name || "clipboard.png",
          bytes,
        );
        insertImage(registerAsset(asset), insertPosition);
        if (typeof insertPosition === "number") {
          insertPosition += 1;
        }
      }
      scheduleSave();
    } catch (error) {
      setNotice({ tone: "error", text: errorText(error) });
    } finally {
      loading = false;
    }
  }

  function insertImage(src: string, position?: number): void {
    if (!editor) return;
    if (typeof position === "number") {
      editor.chain().focus().insertContentAt(position, { type: "image", attrs: { src } }).run();
    } else {
      editor.chain().focus().setImage({ src }).run();
    }
  }

  async function copyPlainText(): Promise<void> {
    if (!editor) return;
    const text = editor.getText({ blockSeparator: "\n" });
    await navigator.clipboard.writeText(text);
    setNotice({ tone: "success", text: "提示词文本已复制。" });
  }

  function registerAsset(asset: PromptDocAsset): string {
    const displaySrc = convertFileSrc(asset.path);
    persistentToDisplay.set(asset.src, displaySrc);
    displayToPersistent.set(displaySrc, asset.src);
    return displaySrc;
  }

  function toDisplayContent(content: unknown, assets: PromptDocAsset[]): unknown {
    displayToPersistent.clear();
    persistentToDisplay.clear();
    for (const asset of assets) {
      registerAsset(asset);
    }
    return mapImageSrc(content, src => persistentToDisplay.get(src) ?? src);
  }

  function toPersistentContent(content: unknown): unknown {
    return mapImageSrc(content, src => displayToPersistent.get(src) ?? src);
  }

  function mapImageSrc(value: unknown, mapper: (src: string) => string): unknown {
    if (Array.isArray(value)) {
      return value.map(item => mapImageSrc(item, mapper));
    }
    if (!value || typeof value !== "object") {
      return value;
    }

    const source = value as Record<string, unknown>;
    const next: Record<string, unknown> = {};
    for (const [key, child] of Object.entries(source)) {
      next[key] = mapImageSrc(child, mapper);
    }

    if (source.type === "image" && next.attrs && typeof next.attrs === "object") {
      const attrs = { ...(next.attrs as Record<string, unknown>) };
      if (typeof attrs.src === "string") {
        attrs.src = mapper(attrs.src);
      }
      next.attrs = attrs;
    }

    return next;
  }

  function emptyDocContent(): JSONContent {
    return { type: "doc", content: [{ type: "paragraph" }] };
  }

  function upsertDocSummary(detail: PromptDocDetail): void {
    const summary: PromptDocSummary = {
      id: detail.id,
      title: detail.title,
      createdAt: detail.createdAt,
      updatedAt: detail.updatedAt,
      plainText: detail.plainText,
    };
    docs = [summary, ...docs.filter(doc => doc.id !== summary.id)].sort(compareDocs);
  }

  function compareDocs(left: PromptDocSummary, right: PromptDocSummary): number {
    return (
      right.updatedAt.localeCompare(left.updatedAt) ||
      left.title.localeCompare(right.title) ||
      left.id.localeCompare(right.id)
    );
  }

  function isImagePath(path: string): boolean {
    const extension = path.split(".").pop()?.toLowerCase() ?? "";
    return IMAGE_EXTENSIONS.has(extension);
  }

  function isActive(name: string, attrs?: Record<string, unknown>): boolean {
    void editorVersion;
    return Boolean(editor?.isActive(name, attrs));
  }
</script>

<section class="prompt-docs">
  <aside class="doc-list">
    <div class="doc-list-header">
      <h2>提示词文档</h2>
      <button type="button" class="btn btn-primary" disabled={loading} onclick={() => void createNewDoc()}>
        新建
      </button>
    </div>

    <input
      class="doc-search"
      type="text"
      placeholder="搜索标题和正文…"
      bind:value={search}
    />

    <div class="doc-items">
      {#if filteredDocs.length === 0}
        <p class="empty-list">{search.trim() ? "没有匹配的文档" : "还没有提示词文档"}</p>
      {:else}
        {#each filteredDocs as doc (doc.id)}
          <button
            type="button"
            class="doc-item"
            class:is-active={activeDoc?.id === doc.id}
            onclick={() => void selectDoc(doc.id)}
          >
            <span class="doc-title">{doc.title}</span>
            <span class="doc-date">{doc.updatedAt}</span>
            {#if doc.plainText.trim()}
              <span class="doc-snippet">{doc.plainText}</span>
            {/if}
          </button>
        {/each}
      {/if}
    </div>
  </aside>

  <main class="doc-editor">
    <div class="editor-titlebar">
      <input
        class="title-input"
        type="text"
        value={title}
        placeholder="未命名文档"
        disabled={!activeDoc || loading}
        oninput={onTitleInput}
      />
      <span class:error={saveState === "error"} class="save-status">{statusText}</span>
      <button type="button" class="btn" disabled={!activeDoc || loading} onclick={copyPlainText}>
        复制全文纯文本
      </button>
      <button type="button" class="btn btn-danger" disabled={!activeDoc || loading} onclick={() => void deleteActiveDoc()}>
        删除
      </button>
    </div>

    <div class="toolbar" aria-label="提示词文档工具栏">
      <button type="button" disabled={!activeDoc} class:is-active={isActive("paragraph")} onclick={() => editor?.chain().focus().setParagraph().run()}>
        正文
      </button>
      <button type="button" disabled={!activeDoc} class:is-active={isActive("heading", { level: 2 })} onclick={() => editor?.chain().focus().toggleHeading({ level: 2 }).run()}>
        标题
      </button>
      <button type="button" disabled={!activeDoc} class:is-active={isActive("bold")} onclick={() => editor?.chain().focus().toggleBold().run()}>
        B
      </button>
      <button type="button" disabled={!activeDoc} class:is-active={isActive("italic")} onclick={() => editor?.chain().focus().toggleItalic().run()}>
        I
      </button>
      <button type="button" disabled={!activeDoc} class:is-active={isActive("bulletList")} onclick={() => editor?.chain().focus().toggleBulletList().run()}>
        列表
      </button>
      <button type="button" disabled={!activeDoc || loading} onclick={() => void chooseImageFiles()}>
        插入图片
      </button>
    </div>

    <div class="editor-shell">
      <div class="editor-surface" class:is-disabled={!activeDoc}>
        <div class="editor-content" bind:this={editorElement}></div>
        {#if !activeDoc}
          <div class="editor-empty">
            <h3>创建一个提示词文档</h3>
            <button type="button" class="btn btn-primary" disabled={loading} onclick={() => void createNewDoc()}>
              新建文档
            </button>
          </div>
        {/if}
      </div>
    </div>
  </main>
</section>

<style>
  .prompt-docs {
    flex: 1;
    min-width: 0;
    min-height: 0;
    display: grid;
    grid-template-columns: 280px minmax(0, 1fr);
    background: var(--bg);
  }

  .doc-list {
    min-height: 0;
    display: flex;
    flex-direction: column;
    gap: 10px;
    padding: 14px;
    background: var(--surface);
    border-right: 1px solid var(--border);
  }

  .doc-list-header {
    display: flex;
    align-items: center;
    justify-content: space-between;
    gap: 10px;
  }

  .doc-list-header h2 {
    font-size: 15px;
  }

  .doc-search {
    width: 100%;
    height: 30px;
    padding: 0 9px;
    border: 1px solid var(--border);
    border-radius: var(--radius-s);
    background: var(--bg);
    color: var(--text);
    outline: none;
  }

  .doc-search:focus {
    border-color: var(--accent);
    box-shadow: var(--focus-ring);
  }

  .doc-items {
    flex: 1;
    min-height: 0;
    overflow: auto;
    display: flex;
    flex-direction: column;
    gap: 6px;
  }

  .doc-item {
    width: 100%;
    display: grid;
    gap: 3px;
    border: 1px solid transparent;
    border-radius: var(--radius-s);
    background: transparent;
    padding: 9px;
    text-align: left;
  }

  .doc-item:hover {
    background: var(--surface-2);
  }

  .doc-item.is-active {
    background: var(--accent-soft);
    border-color: var(--accent-soft-border);
  }

  .doc-title {
    font-weight: 600;
    color: var(--text);
    overflow: hidden;
    white-space: nowrap;
    text-overflow: ellipsis;
  }

  .doc-date {
    font-size: 11px;
    color: var(--text-3);
  }

  .doc-snippet {
    display: -webkit-box;
    overflow: hidden;
    color: var(--text-2);
    font-size: 12px;
    line-height: 1.45;
    line-clamp: 2;
    -webkit-line-clamp: 2;
    -webkit-box-orient: vertical;
  }

  .empty-list {
    padding: 16px 4px;
    color: var(--text-3);
    font-size: 13px;
  }

  .doc-editor {
    min-width: 0;
    min-height: 0;
    display: flex;
    flex-direction: column;
  }

  .editor-titlebar {
    flex: none;
    height: 54px;
    display: flex;
    align-items: center;
    gap: 10px;
    padding: 10px 14px;
    background: var(--surface);
    border-bottom: 1px solid var(--border);
  }

  .title-input {
    flex: 1;
    min-width: 0;
    height: 34px;
    border: 1px solid transparent;
    border-radius: var(--radius-s);
    background: transparent;
    padding: 0 8px;
    font-size: 18px;
    font-weight: 650;
    color: var(--text);
    outline: none;
  }

  .title-input:focus {
    border-color: var(--border-strong);
    background: var(--surface-2);
  }

  .save-status {
    width: 92px;
    flex: none;
    color: var(--text-3);
    font-size: 12px;
  }

  .save-status.error {
    color: var(--danger);
  }

  .toolbar {
    flex: none;
    display: flex;
    align-items: center;
    gap: 6px;
    padding: 8px 14px;
    background: var(--surface);
    border-bottom: 1px solid var(--border);
  }

  .toolbar button {
    min-width: 34px;
    height: 30px;
    border: 1px solid var(--border);
    border-radius: var(--radius-s);
    background: var(--surface);
    color: var(--text-2);
    padding: 0 10px;
    font-size: 13px;
  }

  .toolbar button:hover:not(:disabled),
  .toolbar button.is-active {
    background: var(--accent-soft);
    border-color: var(--accent-soft-border);
    color: var(--accent);
  }

  .toolbar button:nth-child(3),
  .toolbar button:nth-child(4) {
    font-weight: 700;
  }

  .toolbar button:nth-child(4) {
    font-style: italic;
  }

  .editor-shell {
    flex: 1;
    min-height: 0;
    padding: 18px;
    overflow: auto;
  }

  .editor-surface {
    position: relative;
    min-height: 100%;
    max-width: 980px;
    margin: 0 auto;
    background: var(--surface);
    border: 1px solid var(--border);
    border-radius: var(--radius-s);
    box-shadow: var(--shadow-1);
  }

  .editor-surface.is-disabled {
    display: grid;
    place-items: center;
  }

  .editor-content {
    min-height: calc(100vh - 190px);
  }

  .editor-empty {
    position: absolute;
    inset: 0;
    display: grid;
    place-items: center;
    align-content: center;
    gap: 14px;
    background: var(--surface);
    color: var(--text-2);
  }

  .editor-empty h3 {
    font-size: 16px;
  }

  :global(.ProseMirror) {
    min-height: calc(100vh - 190px);
    padding: 36px 44px;
    outline: none;
    color: var(--text);
    line-height: 1.7;
    font-size: 15px;
  }

  :global(.ProseMirror p) {
    margin: 0 0 12px;
  }

  :global(.ProseMirror h1),
  :global(.ProseMirror h2),
  :global(.ProseMirror h3) {
    margin: 18px 0 10px;
    line-height: 1.35;
  }

  :global(.ProseMirror h1) {
    font-size: 24px;
  }

  :global(.ProseMirror h2) {
    font-size: 20px;
  }

  :global(.ProseMirror h3) {
    font-size: 17px;
  }

  :global(.ProseMirror ul),
  :global(.ProseMirror ol) {
    margin: 0 0 12px;
    padding-left: 24px;
  }

  :global(.ProseMirror img) {
    display: block;
    max-width: 100%;
    height: auto;
    margin: 12px 0;
    border-radius: var(--radius-s);
  }

  :global(.ProseMirror-selectednode) {
    outline: 2px solid var(--accent);
  }
</style>
