// src/lib/views/materials/MaterialEditor.svelte
<script lang="ts">
  import { errorText } from "../../utils/format";
  import { workspaceState } from "../../stores/workspace-state.svelte";
  import { onDestroy, onMount } from "svelte";
  import { flip } from "svelte/animate";
  import { flipDuration } from "../../ui/motion";
  import GripVertical from "@lucide/svelte/icons/grip-vertical";
  import { pointerSort, type SortPreview } from "../../utils/pointer-sort";
  import { newMaterialVersion, materialVersionDrafts, moveMaterialVersion, duplicateMaterialVersion } from "../../utils/material-versions";
  import { confirm, open } from "@tauri-apps/plugin-dialog";
  import { inspectMaterialImage, inspectMaterialLibraryImage, saveMaterial, type Material, type MaterialDraft, type MaterialInspection } from "../../api/materials";

  import { tagStore } from "../../stores/tag-store.svelte";
  import { tagColorFor } from "../../utils/tag-colors";
  import { MATERIAL_IMAGE_EXTENSIONS, mergeMaterialMetadata, splitMaterialTags } from "../../utils/materials";
  import { registerCloseGuard } from "../../stores/close-guard";
  import Modal from "../../ui/Modal.svelte";
  import MaterialImage from "./MaterialImage.svelte";
  import { startMaterialGalleryPick } from "../../stores/material-gallery-picker.svelte";
  import type { ImageLoader } from "../../images/image-loader";

  let { material = null, versionId, path = null, remaining = 0, loader, versionLoader, onsaved, onclose }: {
    material?: Material | null; versionId?: number; path?: string | null; remaining?: number; loader: ImageLoader; versionLoader: ImageLoader;
    onsaved: (item: Material) => void; onclose: () => void;
  } = $props();
  let draft = $state<MaterialDraft>({ id: null, title: "", text: "", tags: [], imagePath: null, versions: [newMaterialVersion("默认版本")] });
  let initial = $state("");
  let inspection = $state<MaterialInspection | null>(null);
  let previews = $state<Record<string,string>>({});
  const previewUrls = new Set<string>();
  let imageTarget = $state<"cover" | "version">("cover");
  let activeKey = $state("");
  let sortPreview = $state<SortPreview | null>(null);
  const current = $derived(draft.versions.find(v => v.key === activeKey) ?? draft.versions[0]);
  const activeIndex = $derived(draft.versions.indexOf(current));
  const imageKey = $derived(imageTarget === "cover" ? "cover" : current.key);
  const preview = $derived(previews[imageKey] ?? "");
  function selectVersion(key: string) { activeKey = key; inspection = null; metadataMode = false; selectedSections = []; }
  function selectImageTarget(target: "cover" | "version") { imageTarget = target; inspection = null; metadataMode = false; selectedSections = []; }
  function moveVersion(from: number, to: number) { draft.versions = moveMaterialVersion(draft.versions, from, to); }
  function addVersion(duplicate = false) {
    const version = duplicate ? duplicateMaterialVersion(current) : newMaterialVersion(`版本 ${draft.versions.length + 1}`);
    if (duplicate && previews[current.key]) previews[version.key] = previews[current.key];
    draft.versions = [...draft.versions, version]; selectVersion(version.key); imageTarget = "version";
  }
  async function removeVersion() {
    if (draft.versions.length <= 1) return;
    const target = current;
    if (!(await confirm(`删除版本「${target.name}」？保存素材后生效。`, { title: "删除版本", kind: "warning", okLabel: "删除", cancelLabel: "取消" }))) return;
    if (draft.versions.length <= 1) return;
    draft.versions = draft.versions.filter(v => v.key !== target.key); selectVersion(draft.versions[0].key);
  }
  function useCover() { current.imagePath = null; current.imageSourceId = null; delete previews[current.key]; inspection = null; metadataMode = false; }
  let metadataMode = $state(false);
  let selectedSections = $state<string[]>([]);
  let busy = $state(false);
  let error = $state("");
  let tagQuery = $state("");
  let libraryOpen = $state(false);
  let stopGalleryPick: (() => void) | undefined;
  const availableTags = $derived([...new Set([...tagStore.list.map(t => t.name), ...draft.tags])].filter(name => name.toLowerCase().includes(tagQuery.trim().toLowerCase())));
  const combined = $derived(mergeMaterialMetadata(inspection?.sections ?? [], selectedSections));
  const dirty = $derived(JSON.stringify(draft) !== initial);

  onMount(() => {
    draft = { id: material?.id ?? null, title: material?.title ?? "", text: material?.text ?? "", tags: [...(material?.tags ?? [])], imagePath: null, versions: materialVersionDrafts(material) };
    activeKey = (draft.versions.find(v => v.id === versionId) ?? draft.versions[0]).key;
    initial = JSON.stringify(draft);
    if (path) void inspectImage(path);
    return registerCloseGuard(() => busy ? "素材正在读取或保存" : dirty ? "素材有尚未确认保存的内容" : null);
  });
  onDestroy(() => { stopGalleryPick?.(); for (const url of previewUrls) URL.revokeObjectURL(url); });

  function chooseFromGallery() {
    error = ""; libraryOpen = true;
    stopGalleryPick = startMaterialGalleryPick(rowId => {
      libraryOpen = false;
      if (rowId !== null) void chooseLibraryImage(rowId);
    });
  }

  async function inspectImage(imagePath: string) {
    busy = true; error = "";
    try {
      const result = await inspectMaterialImage(imagePath);
      applyImage(imagePath, result);
    } catch (cause) { error = `无法读取图片：${errorText(cause)}`; }
    finally { busy = false; }
  }
  function applyImage(imagePath: string, result: MaterialInspection) {
    previews[imageKey] = URL.createObjectURL(new Blob([new Uint8Array(result.preview)], { type: "image/png" }));
    previewUrls.add(previews[imageKey]);
    inspection = result;
    if (imageTarget === "cover") draft.imagePath = imagePath;
    else { current.imagePath = imagePath; current.imageSourceId = null; }
    if (!draft.title.trim()) draft.title = result.title;
    metadataMode = false; selectedSections = [];
  }
  async function chooseLibraryImage(rowId: number) {
    busy = true; error = "";
    try {
      const result = await inspectMaterialLibraryImage(rowId);
      applyImage(result.path, result.inspection);
      libraryOpen = false;
    } catch (cause) { error = `无法读取图片：${errorText(cause)}`; }
    finally { busy = false; }
  }
  async function chooseImage() {
    try {
      const result = await open({ multiple: false, directory: false, title: "选择素材展示图", filters: [{ name: "图片", extensions: MATERIAL_IMAGE_EXTENSIONS }] });
      if (typeof result === "string") await inspectImage(result);
    } catch (cause) { error = errorText(cause); }
  }
  async function close() {
    if (busy) return;
    if (libraryOpen) { libraryOpen = false; error = ""; return; }
    if (dirty && !(await confirm("放弃尚未保存的素材内容？", { title: "取消编辑", kind: "warning", okLabel: "放弃", cancelLabel: "继续编辑" }))) return;
    onclose();
  }
  function toggleTag(name: string) { draft.tags = draft.tags.includes(name) ? draft.tags.filter(t => t !== name) : [...draft.tags, name]; }
  function addTags() { draft.tags = [...new Set([...draft.tags, ...splitMaterialTags(tagQuery)])]; tagQuery = ""; }
  async function applyMetadata() {
    const target = current, text = combined;
    if (target.text && target.text !== text && !(await confirm("用所选元数据替换当前文本内容？", { title: "填入元数据", okLabel: "替换", cancelLabel: "取消" }))) return;
    target.text = text;
  }
  async function save() {
    if (busy || (!draft.id && !draft.imagePath)) return;
    draft.text = draft.versions[0].text;
    busy = true; error = "";
    try { const item = await saveMaterial($state.snapshot(draft)); initial = JSON.stringify(draft); onsaved(item); }
    catch (cause) { error = `保存失败，内容已保留：${errorText(cause)}`; }
    finally { busy = false; }
  }
</script>

<Modal open={!libraryOpen && workspaceState.viewMode === "materials"} onclose={() => void close()} {busy} width="900px" labelledby="material-editor-title">
  <div class="editor">
    <header><h2 id="material-editor-title">{material ? "编辑素材" : "确认导入素材"}</h2><span>{remaining > 0 ? `之后还有 ${remaining} 张待确认` : material ? "保存后修改才会生效" : "确认保存后才会添加到素材库"}</span></header>
    <div class="editor-body">
      <div class="cover-column">
        <div class="image-switch" role="group" aria-label="要编辑的图片">
          <button class:active={imageTarget === "cover"} disabled={busy} onclick={() => selectImageTarget("cover")}>固定封面</button>
          <button class:active={imageTarget === "version"} disabled={busy} onclick={() => selectImageTarget("version")}>版本图片</button>
        </div>
        <div class="cover">
          {#if preview}<img src={preview} alt="待保存的图片" />
          {:else if imageTarget === "version" && current.imageSourceId}<MaterialImage id={current.imageSourceId} loader={versionLoader} alt={current.name} />
          {:else if previews.cover}<img src={previews.cover} alt="固定封面" />
          {:else if material}<MaterialImage id={material.id} {loader} alt={material.title} />
          {:else}<span>选择一张展示图</span>{/if}
        </div>
        <small>{imageTarget === "cover" ? "列表卡片始终显示此封面" : `${current.name} · ${current.imagePath || current.imageSourceId ? "独立图片" : "沿用固定封面"}`}</small>
        {#if imageTarget === "version" && (current.imagePath || current.imageSourceId)}<button class="btn" disabled={busy} onclick={useCover}>改用固定封面</button>{/if}
        <button class="btn btn-primary" disabled={busy} onclick={chooseFromGallery}>去画廊选择</button>
        <button class="btn" disabled={busy} onclick={() => void chooseImage()}>{busy ? "处理中…" : "从本地文件选择"}</button>
        <p>支持 PNG、JPG、WebP 等图片。展示图随素材保存。</p>
      </div>
      <fieldset disabled={busy}>
        <label>名称<input bind:value={draft.title} placeholder="例如：黑金礼服" /></label>
        <div class="tag-section">
          <label>Tag<input bind:value={tagQuery} placeholder="搜索或新建 Tag，多个用逗号分隔" onkeydown={e => { if (e.key === "Enter" && !e.isComposing) { e.preventDefault(); addTags(); } }} /></label>
          {#if tagQuery.trim()}<button class="btn" onclick={addTags}>添加输入的 Tag</button>{/if}
          <div class="tags">
            {#each availableTags as name (name)}{@const color = tagColorFor(name, tagStore.list)}
              <button class:selected={draft.tags.includes(name)} aria-pressed={draft.tags.includes(name)} style:--tag-color={color.background} onclick={() => toggleTag(name)}>{draft.tags.includes(name) ? "✓ " : "+ "}{name}</button>
            {/each}
          </div>
          <small>{draft.tags.length ? `已选：${draft.tags.join("、")}` : "未选择 Tag"}</small>
        </div>
        <div class="version-heading"><strong>版本 <small>{draft.versions.length}</small></strong><span>拖动排序 · 第一项默认复制</span></div>
        <div class="version-list" role="list" aria-label="素材版本" class:sorting={!!sortPreview}
          use:pointerSort={{ disabled: busy, onpreview: value => sortPreview = value, onmove: (key, index) => moveVersion(draft.versions.findIndex(v => v.key === key), index) }}>
          {#each draft.versions as version, index (version.key)}
            <div class="version-row" class:active={current.key === version.key} role="listitem" data-sort-key={version.key}
              class:drag-source={sortPreview?.key === version.key} class:drop-before={sortPreview?.beforeKey === version.key}
              class:drop-after={!!sortPreview && sortPreview.beforeKey === null && sortPreview.lastKey === version.key}
              animate:flip={{ duration: flipDuration(180) }}>
              <button type="button" class="grip" data-sort-handle aria-label={`拖动排序 ${version.name}`} title="拖动排序，也可使用右侧上下移动按钮"><GripVertical size={14} strokeWidth={1.5} /></button>
              <button class="version-select" aria-pressed={current.key === version.key} onclick={() => selectVersion(version.key)}><span>{version.name || "未命名版本"}</span>{#if index === 0}<small>默认</small>{/if}</button>
              <button class="move" aria-label={`上移 ${version.name}`} disabled={index === 0} onclick={() => moveVersion(index,index-1)}>↑</button>
              <button class="move" aria-label={`下移 ${version.name}`} disabled={index === draft.versions.length-1} onclick={() => moveVersion(index,index+1)}>↓</button>
            </div>
          {/each}
        </div>
        {#if sortPreview}
          <div class="version-floating" aria-hidden="true" style:left="{sortPreview.left}px" style:top="{sortPreview.top}px" style:width="{sortPreview.width}px">
            <GripVertical size={14} strokeWidth={1.5} /><span>{draft.versions.find(v => v.key === sortPreview?.key)?.name || "未命名版本"}</span>
          </div>
        {/if}
        <div class="version-actions">
          <button class="btn" disabled={draft.versions.length >= 128} onclick={() => addVersion()}>新增版本</button>
          <button class="btn" disabled={draft.versions.length >= 128} onclick={() => addVersion(true)}>复制为新版本</button>
          {#if activeIndex > 0}<button class="text-action" onclick={() => moveVersion(activeIndex,0)}>设为默认</button>{/if}
          <button class="text-action danger" disabled={draft.versions.length <= 1} onclick={() => void removeVersion()}>删除版本</button>
        </div>
        <label>版本名称<input bind:value={current.name} placeholder="例如：无服设、原服设、JK 制服" /></label>
        {#if inspection}
          {#if inspection.warning}<p class="hint">{inspection.warning}</p>{/if}
          {#if inspection.sections.length}
            <div class="metadata">
              <strong>检测到元数据，要用作文本内容吗？</strong>
              <label class="inline"><input type="checkbox" bind:checked={metadataMode} />从元数据选择内容</label>
              {#if metadataMode}
                <div class="metadata-options">{#each inspection.sections as section (section.id)}<label class="inline"><input type="checkbox" bind:group={selectedSections} value={section.id} />{section.label}</label>{/each}</div>
                <label>所选内容预览<textarea class="metadata-preview" readonly value={combined} placeholder="请选择一个或多个区域"></textarea></label>
                <button class="btn" disabled={!selectedSections.length} onclick={() => void applyMetadata()}>将所选内容填入下方文本</button>
              {/if}
            </div>
          {:else}<p class="hint">未发现可提取的提示词文本，可在下方手动填写。</p>{/if}
        {/if}
        <label>文本内容<textarea class="content" bind:value={current.text} placeholder="此版本的提示词或其他文本。"></textarea></label>
      </fieldset>
    </div>
    {#if error}<p class="error" role="alert">{error}</p>{/if}
    <footer><button class="btn" disabled={busy} onclick={() => void close()}>{remaining ? "取消剩余导入" : "取消"}</button><button class="btn btn-primary" disabled={busy || (!draft.id && !draft.imagePath)} onclick={() => void save()}>{busy ? "处理中…" : material ? "保存修改" : remaining ? "确认导入，继续下一张" : "确认导入"}</button></footer>
  </div>
</Modal>

<style>
  .editor { padding: 22px; display: grid; gap: 18px; max-height: 85vh; overflow-y: auto; }
  header, footer { display: flex; align-items: center; justify-content: space-between; gap: 12px; }
  h2 { font-size: var(--font-xl); margin: 0; } header span, p, small { font-size: var(--font-sm); color: var(--text-3); }
  .editor-body { display: grid; grid-template-columns: 250px minmax(0,1fr); gap: 22px; }
  .cover-column { display: flex; flex-direction: column; gap: 12px; }
  .cover { height: 310px; border: 1px solid var(--border); border-radius: 10px; background: var(--surface-2); display: grid; place-items: center; overflow: hidden; color: var(--text-3); }
  .cover img { width: 100%; height: 100%; object-fit: contain; }
  fieldset { display: flex; flex-direction: column; gap: 16px; min-width: 0; margin: 0; padding: 0; border: 0; }
  label { display: flex; flex-direction: column; gap: 7px; font-size: var(--font-sm); }
  input:not([type=checkbox]), textarea { width: 100%; padding: 9px 11px; border: 1px solid var(--border); border-radius: 7px; background: var(--surface); color: var(--text); font: inherit; box-sizing: border-box; }
  textarea { resize: vertical; line-height: 1.6; } .content { min-height: 180px; } .metadata-preview { height: 100px; }
  .tag-section, .metadata { display: grid; gap: 9px; } .metadata { background: var(--surface-2); padding: 12px; border-radius: 8px; }
  .tags { display: flex; flex-wrap: wrap; gap: 6px; max-height: 110px; overflow-y: auto; }
  .tags button { border: 1px solid var(--border); border-radius: var(--radius-full); padding: 5px 9px; background: var(--surface); color: var(--text-2); }
  .tags button.selected { border-color: var(--tag-color); background: var(--accent-soft); color: var(--text); }
  .metadata-options { max-height: 140px; overflow-y: auto; display: grid; gap: 7px; }
  .inline { flex-direction: row; align-items: center; } .hint { margin: 0; line-height: 1.5; }
  .image-switch { display: flex; padding: 3px; gap: 3px; border-radius: 9px; background: var(--surface-2); }
  .image-switch button { flex: 1; border: 0; border-radius: 7px; background: transparent; padding: 7px; font-size: var(--font-sm); color: var(--text-3); transition: background 180ms var(--ease-responsive), color 180ms var(--ease-responsive); }
  .image-switch button.active { color: var(--text); background: var(--surface); box-shadow: var(--shadow-1); }
  .version-heading { display: flex; align-items: center; justify-content: space-between; font-size: var(--font-sm); }
  .version-heading span { font-size: 11px; color: var(--text-3); }
  .version-list { display: grid; gap: 4px; max-height: 180px; overflow-y: auto; padding: 3px 0; overscroll-behavior: contain; }
  .version-row { position: relative; display: flex; align-items: center; border: 1px solid transparent; border-radius: 8px; transition: background 180ms var(--ease-responsive), border-color 180ms var(--ease-responsive); }
  .version-row.active { background: var(--accent-soft); border-color: var(--accent-soft-border); }
  .version-select { display: flex; align-items: center; gap: 8px; flex: 1; min-width: 0; padding: 8px; border: 0; background: transparent; text-align: left; font-size: var(--font-sm); }
  .version-select > span { overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
  .version-select small { flex: none; margin-left: auto; color: var(--accent); font-size: 10px; }
  .grip { display: grid; place-items: center; padding: 8px 5px; border: 0; background: transparent; color: var(--text-3); cursor: grab; touch-action: none; user-select: none; }
  .grip:active, .sorting { cursor: grabbing; }
  .drag-source { opacity: 0.3; }
  .drop-before::before, .drop-after::after { content: ""; position: absolute; height: 2px; left: 2px; right: 2px; background: var(--accent); border-radius: 2px; pointer-events: none; }
  .drop-before::before { top: -3px; } .drop-after::after { bottom: -3px; }
  .version-floating { position: fixed; z-index: var(--z-menu); display: flex; align-items: center; gap: 8px; padding: 8px; box-sizing: border-box; border: 1px solid var(--accent-soft-border); border-radius: 8px; background: var(--surface); box-shadow: var(--shadow-2); color: var(--text); font-size: var(--font-sm); pointer-events: none; }
  .version-floating span { overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
  .move { border: 0; background: transparent; color: var(--text-3); padding: 5px 7px; }
  .version-actions { display: flex; flex-wrap: wrap; align-items: center; gap: 8px; }
  .version-actions .btn { font-size: var(--font-sm); padding: 4px 8px; }
  .text-action { border: 0; background: transparent; color: var(--accent); font-size: var(--font-sm); padding: 4px; }
  .text-action.danger { color: var(--danger); }
  .error { color: var(--danger); } footer { justify-content: flex-end; }
  @media (prefers-reduced-motion: reduce) { .image-switch button, .version-row { transition: none; } }
  @media (max-width: 720px) { .editor-body { grid-template-columns: 1fr; } .cover { height: 190px; } header { align-items: start; flex-direction: column; } }
</style>

// src/react/views/materials/MaterialEditor.tsx
import { useEffect, useRef, useState } from "react";
import { open } from "@tauri-apps/plugin-dialog";
import { GripVertical } from "lucide-react";
import { inspectMaterialImage, inspectMaterialLibraryImage, saveMaterial, type MaterialDraft, type MaterialInspection, type MaterialVersionDraft } from "../../../lib/api/materials";
import { materialVersionDrafts, newMaterialVersion, duplicateMaterialVersion, moveMaterialVersion } from "../../../lib/utils/material-versions";
import { MATERIAL_IMAGE_EXTENSIONS, splitMaterialTags, mergeMaterialMetadata } from "../../../lib/utils/materials";
import { pointerSort, type SortPreview } from "../../../lib/utils/pointer-sort";
import { registerCloseGuard } from "../../../lib/stores/close-guard";
import { errorText } from "../../../lib/utils/format";
import { useLibrary } from "../../state/library";
import { useMaterials, materialCovers, materialVersionCovers, materialSaved, closeMaterialEditor, startMaterialGalleryPick } from "../../state/materials";
import { runTask } from "../../state/tasks";
import { Button, Checkbox, Input, Modal, Textarea } from "../../ui/controls";
import { MaterialImage } from "./MaterialImage";

export function MaterialEditor({ active = true }: { active?: boolean }) {
  const { editing: material, editingVersion, pendingPaths } = useMaterials.getState();
  const [draft, setDraft] = useState<MaterialDraft>(() => ({ id: material?.id ?? null, title: material?.title ?? "", text: material?.text ?? "", tags: [...material?.tags ?? []], imagePath: null, versions: materialVersionDrafts(material) }));
  const initial = useRef(JSON.stringify(draft));
  const [activeKey, setActiveKey] = useState(() => (draft.versions.find(v => v.id === editingVersion) ?? draft.versions[0]).key);
  const [imageTarget, setImageTarget] = useState<"cover" | "version">("cover");
  const [previews, setPreviews] = useState<Record<string, string>>({}); const urls = useRef(new Set<string>());
  const [inspection, setInspection] = useState<MaterialInspection | null>(null); const [metadataMode, setMetadataMode] = useState(false); const [sections, setSections] = useState<string[]>([]);
  const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [tagQuery, setTagQuery] = useState("");
  const [confirm, setConfirm] = useState<{ title: string; text: string; action: () => void } | null>(null);
  const [sortPreview, setSortPreview] = useState<SortPreview | null>(null); const [listNode, setListNode] = useState<HTMLDivElement | null>(null);
  const current = draft.versions.find(version => version.key === activeKey) ?? draft.versions[0];
  const activeIndex = draft.versions.indexOf(current); const imageKey = imageTarget === "cover" ? "cover" : current.key;
  const combined = mergeMaterialMetadata(inspection?.sections ?? [], sections);
  const libraryTags = useLibrary(state => state.tags);
  const availableTags = [...new Set([...libraryTags.map(tag => tag.name), ...draft.tags])].filter(name => name.toLowerCase().includes(tagQuery.trim().toLowerCase()));
  const guard = useRef({ busy, dirty: false }); guard.current = { busy, dirty: JSON.stringify(draft) !== initial.current };
  const alive = useRef(true);
  const sortMove = useRef((key: string, to: number) => { setDraft(value => ({ ...value, versions: moveMaterialVersion(value.versions, value.versions.findIndex(v => v.key === key), to) })); });
  useEffect(() => { if (!listNode) return; const sort = pointerSort(listNode, { disabled: busy, onpreview: setSortPreview, onmove: (key, index) => sortMove.current(key, index) }); return () => sort.destroy(); }, [busy, listNode]);
  useEffect(() => {
    alive.current = true; const unregister = registerCloseGuard(() => guard.current.busy ? "素材正在读取或保存" : guard.current.dirty ? "素材有尚未确认保存的内容" : null);
    return () => { alive.current = false; unregister(); for (const url of urls.current) URL.revokeObjectURL(url); };
  }, []);
  const importStarted = useRef(false);
  useEffect(() => { if (pendingPaths[0] && !importStarted.current) { importStarted.current = true; void inspect(pendingPaths[0]); } }, []);
  function updateVersion(patch: Partial<MaterialVersionDraft>) { setDraft(value => ({ ...value, versions: value.versions.map(version => version.key === current.key ? { ...version, ...patch } : version) })); }
  function resetMetadata() { setInspection(null); setMetadataMode(false); setSections([]); }
  function selectVersion(key: string) { setActiveKey(key); resetMetadata(); }
  function move(from: number, to: number) { setDraft(value => ({ ...value, versions: moveMaterialVersion(value.versions, from, to) })); }
  function addVersion(duplicate: boolean) {
    const version = duplicate ? duplicateMaterialVersion(current) : newMaterialVersion(`版本 ${draft.versions.length + 1}`);
    if (duplicate && previews[current.key]) setPreviews(value => ({ ...value, [version.key]: previews[current.key] }));
    setDraft(value => ({ ...value, versions: [...value.versions, version] })); selectVersion(version.key); setImageTarget("version");
  }
  function applyImage(path: string, result: MaterialInspection, target: string) {
    if (!alive.current) return;
    const url = URL.createObjectURL(new Blob([new Uint8Array(result.preview)], { type: "image/png" })); urls.current.add(url);
    setPreviews(value => ({ ...value, [target]: url })); setInspection(result); setSections([]); setMetadataMode(false);
    setDraft(value => ({ ...value, title: value.title.trim() ? value.title : result.title, ...(target === "cover" ? { imagePath: path } : { versions: value.versions.map(version => version.key === target ? { ...version, imagePath: path, imageSourceId: null } : version) }) }));
  }
  async function inspect(path: string) { setBusy(true); setError(""); const target = imageKey; try { applyImage(path, await inspectMaterialImage(path), target); } catch (cause) { if (alive.current) setError(`无法读取图片：${errorText(cause)}`); } finally { if (alive.current) setBusy(false); } }
  async function chooseLocal() { try { const path = await open({ multiple: false, directory: false, title: "选择素材展示图", filters: [{ name: "图片", extensions: MATERIAL_IMAGE_EXTENSIONS }] }); if (typeof path === "string") await inspect(path); } catch (cause) { setError(errorText(cause)); } }
  async function chooseLibrary(id: number, target: string) { setBusy(true); setError(""); try { const result = await inspectMaterialLibraryImage(id); applyImage(result.path, result.inspection, target); } catch (cause) { if (alive.current) setError(`无法读取图片：${errorText(cause)}`); } finally { if (alive.current) setBusy(false); } }
  function chooseFromGallery() {
    const target = imageKey;
    startMaterialGalleryPick(imageTarget === "cover" ? "固定封面" : `版本「${current.name}」`, id => void chooseLibrary(id, target));
  }
  function close() { if (busy) return; if (guard.current.dirty) setConfirm({ title: "取消编辑", text: "放弃尚未保存的素材内容？", action: closeMaterialEditor }); else closeMaterialEditor(); }
  function addTags() { setDraft(value => ({ ...value, tags: [...new Set([...value.tags, ...splitMaterialTags(tagQuery)])] })); setTagQuery(""); }
  async function save() {
    if (busy || (!draft.id && !draft.imagePath)) return;
    const directory = useLibrary.getState().snapshot?.dataDirectory;
    setBusy(true); setError(""); const value = { ...draft, text: draft.versions[0].text };
    try { const item = await runTask("保存素材", () => saveMaterial(value)); if (alive.current && directory === useLibrary.getState().snapshot?.dataDirectory) { initial.current = JSON.stringify(value); materialSaved(item); } }
    catch (cause) { if (alive.current) setError(`保存失败，内容已保留：${errorText(cause)}`); }
    finally { if (alive.current) setBusy(false); }
  }
  return <><Modal open={active} onClose={close} busy={busy} title={material ? "编辑素材" : "确认导入素材"} description={pendingPaths.length > 1 ? `之后还有 ${pendingPaths.length - 1} 张待确认` : "确认保存后修改才会生效"} width={900} footer={<><Button disabled={busy} onClick={close}>{pendingPaths.length > 1 ? "取消剩余导入" : "取消"}</Button><Button variant="primary" disabled={busy || (!draft.id && !draft.imagePath)} onClick={() => void save()}>{busy ? "处理中…" : material ? "保存修改" : pendingPaths.length > 1 ? "确认导入，继续下一张" : "确认导入"}</Button></>}>
    <div className="rm-editor"><div className="rm-cover-column"><div className="rm-image-switch"><Button disabled={busy} variant="ghost" aria-pressed={imageTarget === "cover"} onClick={() => { setImageTarget("cover"); resetMetadata(); }}>固定封面</Button><Button disabled={busy} variant="ghost" aria-pressed={imageTarget === "version"} onClick={() => { setImageTarget("version"); resetMetadata(); }}>版本图片</Button></div>
      <div className="rm-cover">{previews[imageKey] ? <img src={previews[imageKey]} alt="待保存图片" /> : imageTarget === "version" && current.imageSourceId ? <MaterialImage id={current.imageSourceId} loader={materialVersionCovers} alt={current.name} /> : previews.cover ? <img src={previews.cover} alt="固定封面" /> : material ? <MaterialImage id={material.id} loader={materialCovers} alt={material.title} /> : <span>选择一张展示图</span>}</div>
      <small>{imageTarget === "cover" ? "列表卡片始终显示此封面" : `${current.name} · ${current.imagePath || current.imageSourceId ? "独立图片" : "沿用固定封面"}`}</small>
      {imageTarget === "version" && (current.imagePath || current.imageSourceId) && <Button disabled={busy} onClick={() => { updateVersion({ imagePath: null, imageSourceId: null }); setPreviews(value => { const next = { ...value }; delete next[current.key]; return next; }); resetMetadata(); }}>改用固定封面</Button>}
      <Button variant="primary" disabled={busy} onClick={chooseFromGallery}>去画廊选择</Button><Button disabled={busy} onClick={() => void chooseLocal()}>从本地文件选择</Button><small>支持 PNG、JPG、WebP 等图片。展示图随素材保存。</small>
    </div><fieldset disabled={busy} className="rm-fields"><label>名称<Input value={draft.title} onChange={event => setDraft(value => ({ ...value, title: event.target.value }))} placeholder="例如：黑金礼服" /></label>
      <label>Tag<Input value={tagQuery} placeholder="搜索或新建 Tag，多个用逗号分隔" onChange={event => setTagQuery(event.target.value)} onKeyDown={event => { if (event.key === "Enter" && !event.nativeEvent.isComposing) { event.preventDefault(); addTags(); } }} /></label>
      {tagQuery.trim() && <Button onClick={addTags}>添加输入的 Tag</Button>}<div className="rm-tags">{availableTags.map(name => <Button size="sm" key={name} aria-pressed={draft.tags.includes(name)} variant={draft.tags.includes(name) ? "primary" : "default"} onClick={() => setDraft(value => ({ ...value, tags: value.tags.includes(name) ? value.tags.filter(tag => tag !== name) : [...value.tags, name] }))}>{name}</Button>)}</div><small>{draft.tags.length ? `已选：${draft.tags.join("、")}` : "未选择 Tag"}</small>
      <div className="rm-version-heading"><strong>版本 · {draft.versions.length}</strong><small>拖动排序 · 第一项默认复制</small></div>
      <div className="rm-version-list" ref={setListNode} role="list" aria-label="素材版本">{draft.versions.map((version, index) => <div className={`rm-version-row ${version.key === current.key ? "is-active" : ""} ${sortPreview?.beforeKey === version.key ? "drop-before" : ""} ${sortPreview?.key === version.key ? "is-dragging" : ""}`} role="listitem" data-sort-key={version.key} key={version.key}><Button size="icon" variant="ghost" data-sort-handle aria-label={`拖动排序 ${version.name}`}><GripVertical size={14} /></Button><button className="rm-version-select" aria-pressed={version.key === current.key} onClick={() => selectVersion(version.key)}><span>{version.name || "未命名版本"}</span>{index === 0 && <small>默认</small>}</button><Button size="icon" variant="ghost" aria-label={`上移 ${version.name}`} disabled={index === 0} onClick={() => move(index, index - 1)}>↑</Button><Button size="icon" variant="ghost" aria-label={`下移 ${version.name}`} disabled={index === draft.versions.length - 1} onClick={() => move(index, index + 1)}>↓</Button></div>)}</div>
      <div className="rm-version-actions"><Button size="sm" disabled={draft.versions.length >= 128} onClick={() => addVersion(false)}>新增版本</Button><Button size="sm" disabled={draft.versions.length >= 128} onClick={() => addVersion(true)}>复制为新版本</Button>{activeIndex > 0 && <Button size="sm" onClick={() => move(activeIndex, 0)}>设为默认</Button>}<Button size="sm" variant="danger" disabled={draft.versions.length <= 1} onClick={() => setConfirm({ title: "删除版本", text: `删除版本「${current.name}」？保存素材后生效。`, action: () => { setDraft(value => ({ ...value, versions: value.versions.filter(version => version.key !== current.key) })); setActiveKey(draft.versions.find(version => version.key !== current.key)!.key); resetMetadata(); } })}>删除版本</Button></div>
      <label>版本名称<Input value={current.name} onChange={event => updateVersion({ name: event.target.value })} /></label>
      {inspection && <div className="rm-metadata">{inspection.warning && <p>{inspection.warning}</p>}{inspection.sections.length ? <><label className="rm-inline"><Checkbox checked={metadataMode} onCheckedChange={value => setMetadataMode(value === true)} />从元数据选择内容</label>{metadataMode && <>{inspection.sections.map(section => <label className="rm-inline" key={section.id}><Checkbox checked={sections.includes(section.id)} onCheckedChange={() => setSections(value => value.includes(section.id) ? value.filter(id => id !== section.id) : [...value, section.id])} />{section.label}</label>)}<Textarea aria-label="所选内容预览" readOnly value={combined} /><Button disabled={!sections.length} onClick={() => current.text && current.text !== combined ? setConfirm({ title: "填入元数据", text: "用所选元数据替换当前文本内容？", action: () => updateVersion({ text: combined }) }) : updateVersion({ text: combined })}>将所选内容填入下方文本</Button></>}</> : <p>未发现可提取的提示词文本，可在下方手动填写。</p>}</div>}
      <label>文本内容<Textarea className="rm-content" value={current.text} onChange={event => updateVersion({ text: event.target.value })} placeholder="此版本的提示词或其他文本。" /></label>
    </fieldset></div>{error && <p className="rm-error" role="alert">{error}</p>}
  </Modal>
  <Modal open={active && !!confirm} onClose={() => setConfirm(null)} title={confirm?.title ?? "确认"} footer={<><Button onClick={() => setConfirm(null)}>取消</Button><Button variant="primary" onClick={() => { const action = confirm?.action; setConfirm(null); action?.(); }}>确认</Button></>}><p>{confirm?.text}</p></Modal>
  {sortPreview && <div className="rm-sort-floating" style={{ left: sortPreview.left, top: sortPreview.top, width: sortPreview.width }}><GripVertical size={14} />{draft.versions.find(version => version.key === sortPreview.key)?.name}</div>}
  </>;
}
